### PR TITLE
fix: adapting operate to get from the right repo

### PR DESCRIPTION
**Pull request by marcosgvieira**
Adapting:

- release-generation should be triggered with the right pattern
- Operate to get from the correct repo depending on the version

### CODE REVIEW

**Comment by marcosgvieira** [comment]
@jessesimpson36 and @aabouzaid I did small adjustments that may help and fix the issue with the release notes fetcher and save some time for the next release, can you do a quick check when you find time?

**Comment by aabouzaid** [comment]
I will leave this to @jessesimpson36 since Jesse worked on it much more.

**Comment by jessesimpson36** [comment]
I added a couple commits. just minor touchups. one replaces print statements with logs, and the other parses the major/minor version number inside the github actions so that when 8.6 or 8.7 comes around,  the if statements don't need to be updated. 

I plan on making a test repo with a test github actions script just to make sure that major/minor parsing logic I added didn't break anything.

**Comment by jessesimpson36** [comment]
Doing tests in this repo: https://github.com/jessesimpson36/gha_test

**Comment by jessesimpson36** [comment]
No worries, I was pretty close anyway. I have it tested in my 
https://github.com/jessesimpson36/gha_test/actions
test repo: 

|    Test  name   |   Link   |
| -----------------   |  -------- |
| < 8.4 generation | https://github.com/jessesimpson36/gha_test/actions/runs/9656015039/job/26632816589 |
| >= 8.5 generation | https://github.com/jessesimpson36/gha_test/actions/runs/9672127761/job/26683906142 |
| < 8.4 semver syntax | https://github.com/jessesimpson36/gha_test/actions/runs/9672134114/job/26683925534 | 
| >= 8.5 semver syntax | https://github.com/jessesimpson36/gha_test/actions/runs/9672138072/job/26683937108 |

Given that each of these scenarios demonstrate working conditionals I added to the github actions, I feel pretty confident that this PR will work next release.

**Review by jessesimpson36 — APPROVED** [review]

**Comment by jessesimpson36** [comment]
Merge when ready, or feel free to critique the changes I added.

**Pull request merged**
