### PR TITLE
Update to Camunda 8.3.0

### PR DESCRIPTION
**Pull request by megglos**

### CODE REVIEW

**Comment by megglos** [comment]
@CatalinaMoisuc @jfriedenstab  could you take look here please? web-modeler test fails, do we need to bump postgres or something?

**Comment by jfriedenstab** [comment]
@megglos I think we need to bump Keycloak, because the latest version of Identity only supports Keycloak 21 and 22 (if I'm not mistaken). When I run Camunda locally, the Identity container is failing with a `BadRequestException` when it tries to create the realm config in Keycloak.

**Comment by megglos** [comment]
now Optimize tests fail @camunda/distribution can you please take a look here with @camunda/optimize ?

**Comment by megglos** [comment]
in the meantime I would already create a release from this branch to make the release notes available

**Comment by megglos** [comment]
thanks @jessesimpson36 🙌

**Comment by jessesimpson36** [comment]
Yup!

**Pull request merged**
