### PR TITLE
chore(platform): bump to 8.2.0 release

### PR DESCRIPTION
**Pull request by megglos**
Given all core C8 components are ready we can bump to the new release.

### CODE REVIEW

**Comment by dlavrenuek** [comment]
@megglos I have added some changes:
- a new flag for "Resource authorizations"
- database configuration in Identity that is needed to store resource authorizations
- added the resource authorizations flag and Identity base url in Operate config - @johanwelgemoed can you review if the env name is correct?
- added the resource authorizations flag and Identity base url in Tasklist config - @marcosgvieira can you review if the env name is correct?
- removed custom connectors client - it is now initialized with a single line of configuration

**Review by dlavrenuek — APPROVED** [review]
🎉

**Comment by dlavrenuek** [comment]
Shall we also add a short section about resource authorizations in the readme and how to enable them?

**Comment by megglos** [comment]
> Shall we also add a short section about resource authorizations in the readme and how to enable them?

that would be great!

**Comment by vsgoulart** [comment]
@megglos @dlavrenuek Please check my last commit. I had to wait for the health checks for Identity on the Tasklist service because if we start Tasklist with the demo data profile Identity would break

You can test it by changing [this line](https://github.com/camunda/camunda-platform/blob/main/docker-compose.yaml#L86) to `- SPRING_PROFILES_ACTIVE=dev-data,identity-auth`

Feel free to remove my commit if this is not the best solution/incorrect in your opinion

**Comment by megglos** [comment]
> @megglos @dlavrenuek Please check my last commit. I had to wait for the health checks for Identity on the Tasklist service because if we start Tasklist with the demo data profile Identity would break

If I got you right, this is only something that is relevant if profiles are changed? And in that case tasklist would run into issues if identity is not ready? I don't see an issue with taking it over regardless but also don't see strong need for it.

**Comment by vsgoulart** [comment]
> > @megglos @dlavrenuek Please check my last commit. I had to wait for the health checks for Identity on the Tasklist service because if we start Tasklist with the demo data profile Identity would break
> 
> If I got you right, this is only something that is relevant if profiles are changed? And in that case tasklist would run into issues if identity is not ready? I don't see an issue with taking it over regardless but also don't see strong need for it, assuming it requires modifications of the profiles to be an issue.

@megglos Yeah, it only fixes an issue if we change the profile. But it shouldn't have any impact if any user just uses it as is

**Comment by megglos** [comment]
@vsgoulart I just run the stack accessing tasklist with the user `demo` fails though. The user has the `Tasklist` role in identity. Access to Operate works, can you please check what's off in relation to Tasklist?
image

**Comment by vsgoulart** [comment]
> @vsgoulart I just ran the stack, accessing tasklist with the user `demo` fails though. The user has the `Tasklist` role in identity. Access to Operate works, can you please check what's off in relation to Tasklist? image

@megglos I just tested and the culprit seems to be `RESOURCE_AUTHORIZATIONS_ENABLED`, I enabled it and worked. I tried with my changes and with the original version of `depends_on`

**Comment by marcosgvieira** [comment]
> > @vsgoulart I just ran the stack, accessing tasklist with the user `demo` fails though. The user has the `Tasklist` role in identity. Access to Operate works, can you please check what's off in relation to Tasklist? image
> 
> @megglos I just tested and the culprit seems to be `RESOURCE_AUTHORIZATIONS_ENABLED`, I enabled it and worked. I tried with my changes and with the original version of `depends_on`

@megglos and @vsgoulart the issue on tasklist is happening because we are checking the baseurl to go to identity in one place, so when this is configured and resource_permissions are disabled on identity we get a 403. So currently to have `CAMUNDA_TASKLIST_IDENTITY_BASEURL` configured on tasklist we need `${RESOURCE_AUTHORIZATIONS_ENABLED}=true`. In case it's false we should leave it blank.

I will add a fix to tasklist in this place to look first on Resource Authorizations Enabled before going to identity, but unfortunately it will not be part of 8.2

**Comment by megglos** [comment]
@marcosgvieira thanks for looking into this! So given we remove all the resource_auth additions tasklist should work fine? If so I would opt for extracting those changes into a separate PR, to keep this one focused on just updating the versions for the 8.2 release, without any additions.

**Comment by megglos** [comment]
@dlavrenuek I extracted the resource based auth changed to a new PR https://github.com/camunda/camunda-platform/pull/116 can you take it from there? I would get this one merged as without the new config the 8.2.0 stack works for now.

@marcosgvieira @dlavrenuek please follow-up there on the issue with tasklist when using these new env vars and actually disabling the resource auth

**Pull request merged**
