### PR TITLE
docs: introduce Desktop Modeler deployment

### PR DESCRIPTION
**Pull request by nikku**
`keycloak` name is not exposed under normal circumstances, outside of the internal network.

### CODE REVIEW

**Review by megglos — APPROVED** [review]
LGTM! Looping in @jessesimpson36 as this component is owned by @camunda/distribution

**Comment by jessesimpson36** [comment]
Does this PR solve a problem? from my understanding, both the url 
http://keycloak:8080/auth/realms/camunda-platform/protocol/openid-connect/token
and
http://localhost:18080/auth/realms/camunda-platform/protocol/openid-connect/token

seems to be valid to me.  The question is whether you want your network traffic to travel within the docker network named `keycloak`  or whether you want the traffic to travel out of the docker network, onto the host, and back inside of the docker network. 

I'll run some tests just for validating.

**Comment by jessesimpson36** [comment]
Also,  although the keycloak service is not exposed externally,  the web modeler webserver  should still able to access keycloak in this way.

**Comment by jessesimpson36** [comment]
I just tested using 

http://keycloak:8080/auth/realms/camunda-platform/protocol/openid-connect/token

And deploying a model with that url works.

When I use 
http://localhost:18080/auth/realms/camunda-platform/protocol/openid-connect/token

deploying a model does not work. I'm 90% sure the reason for this is that localhost resolves to the web-modeler container rather than the keycloak container.

**Comment by nikku** [comment]
I think we need to solve two different issues:

* From within the image (using web modeler) the URL is `http://keycloak...`.
* From outside the image (using Desktop Modeler) the URL is `http://localhost...`

Happy to also document both URLs. As a user of the core offering (not enterprise customer) I'm of course leaning towards making this Desktop Modeler first.

**Comment by nikku** [comment]
Changed this PR via https://github.com/camunda/camunda-platform/pull/428/commits/c3086d2f75062bb5cd9b93f11ce34a185f7e469d to introduce a dedicated desktop modeler section, with the specific ports exposed.

**Comment by nikku** [comment]
@jessesimpson36 Not sure how this could automatically merge, without your approval. Please double check my latest changes. I believe they are what we want, but happy to follow-up with another PR to fix what you believe needs fixing.

**Pull request merged**
