### PR TITLE
feat(platform): Update to 8.3.0-alpha4

### PR DESCRIPTION
**Pull request by megglos**

### CODE REVIEW

**Comment by megglos** [comment]
@jessesimpson36 @npepinpe since https://github.com/camunda/zeebe/pull/13706 we don't have curl available in the zeebe dist anymore, as also there is no wget I went for a plain tcp check as health indicator for now

Do you see any better alternatives?

**Comment by megglos** [comment]
will merge for now to unblock the alpha release but let's follow-up on this

**Comment by jessesimpson36** [comment]
I've never seen this `:> ` operator, but if the healthcheck works, then I have no issues!  I mean, unless we're on an image that has bash compiled without support for network redirections ( the feature that /dev/tcp/host/port uses).

Also, I may have backported healthchecks to the stable branches. :sweat_smile:

**Comment by megglos** [comment]
> Also, I may have backported healthchecks to the stable branches. 😅

At least on stable/8.2 there are no health checks, now I checked 8.1 an there they are 😅 but 8.1 still has curl with the current patch, will fail next time we update then ^^

**Comment by jessesimpson36** [comment]
That's so strange. there should be healthchecks on all of them.  Sometimes github does some merge-conflict resolution, and I'm wondering if the healthcheck change didn't make it.  I'd like to add the healthchecks back in to each stable branch (8.1 and 8.2).  

A minor concern I have is that some components are looking to switch to using alpine, which I think might break the `:> /dev/tcp ` redirection

I'll try to get to this soon, but not when I have as many tickets as I'm currently dealing with.

**Pull request merged**
