### PR TITLE
chore(docker-compose): update Web Modeler to 0.4.0-beta

### PR DESCRIPTION
**Pull request by jfriedenstab**
see https://github.com/camunda/web-modeler/issues/3443

### CODE REVIEW

**Review by pihme — COMMENTED** [review]
Not sure if it is caused by your changes, but I get en error when I want to start this configuration:

```
❯ docker-compose -f docker-compose.yaml -f docker-compose-web-modeler-beta.yaml up -d
WARNING: The JAVA_OPTIONS variable is not set. Defaulting to a blank string.
Creating network "camunda-platform_modeler" with the default driver
Creating network "camunda-platform_camunda-platform" with the default driver
Creating network "camunda-platform_identity-network" with the default driver
Creating modeler-db         ... done
Creating modeler-websockets ... done
Creating mailhog            ... done
Creating postgres           ... done
Creating elasticsearch      ... done
Creating keycloak           ... done
Creating zeebe              ... done
Creating identity           ... done
Creating operate            ... done
Creating optimize           ... done
Creating tasklist           ... done
Creating connectors         ... done
Creating modeler-restapi    ... 
Creating modeler-restapi    ... error

ERROR: for modeler-restapi  Cannot start service modeler-restapi: driver failed programming external connectivity on endpoint modeler-restapi (4c249a254228f96006bed7fb8a89ca1e6b7adab0ce4049f9f811002f2c95a039): Bind for 0.0.0.0:8085 failed: port is already allocated

ERROR: for modeler-restapi  Cannot start service modeler-restapi: driver failed programming external connectivity on endpoint modeler-restapi (4c249a254228f96006bed7fb8a89ca1e6b7adab0ce4049f9f811002f2c95a039): Bind for 0.0.0.0:8085 failed: port is already allocated
ERROR: Encountered errors while bringing up the project.
```

Can you reproduce this?

**Comment by jfriedenstab** [comment]
Oh, it looks like the `connectors-bundle` is now listening on port `8085` as well. I didn't notice it because I had disabled it in my tests. It's clashing now with this line:
https://github.com/camunda/camunda-platform/blob/52829ccd91201c0c0c02826d09b8b6b9e36e68b5/docker-compose-web-modeler-beta.yaml#L78
Actually, I don't think that we need to expose port `8081` of the restapi at all (it's not supposed to be accessed directly). So we could just remove that line completely.

**Comment by jfriedenstab** [comment]
@pihme: I removed the exposed port for the restapi. Could you please try again?

**Review by pihme — APPROVED** [review]
Works now

**Pull request merged**
