### PR TITLE
deps: bump connectors-bundle

### PR DESCRIPTION
**Pull request by igpetrov**
- Core: working
- Full package: disabling inbound polling for the time-being until I figure out how to connect it to the Keycloak

### CODE REVIEW

**Comment by tmetzke** [comment]
@igpetrov, is this ready for review? Is anything left open here?

**Comment by igpetrov** [comment]
Hi @tmetzke 

That's the one I mentioned today on a daily meeting. Currently cannot wire connectors runtime to Operate when Keycloak involved.

Working on it now.

**Comment by igpetrov** [comment]
For now disabling polling for keycloak setup. Will look into it later this week (now focusing on few bug-fixes)

@tmetzke

**Comment by berndruecker** [comment]
@igpetrov KEycloak setup works for me - but I need to add permissions for the operate application manually via Idenity console. Checking if that could be automated at the moment: https://camunda.slack.com/archives/CRQAL5A1M/p1671550796708539

grafik

Here my config that worked:

```yaml
  connectors: # https://docs.camunda.io/docs/components/integration-framework/connectors/out-of-the-box-connectors/available-connectors-overview/
    image: camunda/connectors-bundle:${CAMUNDA_CONNECTORS_VERSION:-0.14.1}
    container_name: connectors
    ports:
      - "8085:8080"
    environment:
      - ZEEBE_CLIENT_BROKER_GATEWAY-ADDRESS=zeebe:26500
      - ZEEBE_CLIENT_SECURITY_PLAINTEXT=true
      - CAMUNDA_OPERATE_CLIENT_KEYCLOAK-URL=http://keycloak:8080
      - CAMUNDA_OPERATE_CLIENT_CLIENT-ID=operate
      - CAMUNDA_OPERATE_CLIENT_CLIENT-SECRET=XALaRPl5qwTEItdwCMiPS62nVpKs7dL7
      - CAMUNDA_OPERATE_CLIENT_KEYCLOAK-REALM=camunda-platform
      - CAMUNDA_OPERATE_CLIENT_URL=http://operate:8080
    env_file: connector-secrets.txt
    networks:
      - camunda-platform
      - identity-network
    depends_on:
      - zeebe
      - operate
      - identity
```

**Review by markfarkas-camunda — APPROVED** [review]
Thank you for also updating  to the latest connectors-bundle version 👍

**Pull request merged**
