### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by akeller**
From a discussion in the C8 Stakeholder meeting - Small restructuring adjustments. Added emphasis that Docker Compose is for development only.

### CODE REVIEW

**Comment by akeller** [comment]
@hisImminence, I added you as a reviewer mostly for awareness: no significant changes but just more emphasis on Docker Composer as a development option.

**Comment by akeller** [comment]
@christinaausley I did not update or read the entire README. Depending on your bandwidth, you can consider that outside of the scope of this review and just look at the changes I made.

**Review by christinaausley — APPROVED** [review]
I don't have adjustments here 👍

**Comment by falko** [comment]
Sorry, if I'm late to the game but instead of guiding people directly to only one specific production deployment option we should ask them to view our documentation page that explains all options and combinations for production and development deployments so that they can make an informed decision and maybe even use SaaS instead of docker compose. It may also sound as if docker compose is out recommend dev environment while it's only ranked the 3rd best option.

**Pull request merged**
