### PR TITLE
feat: add Optimize to monorepo release notes

### PR DESCRIPTION
**Pull request by misiekhardcore**
This PR adds Optimize to the release note generation.

related to https://github.com/camunda/camunda/issues/22258

### CODE REVIEW

**Comment by misiekhardcore** [comment]
I think the GH token is missing permissions to read from `camunda/camunda-optimize` repository

**Comment by aabouzaid** [comment]
LGTM, but I will leave this to @jessesimpson36 as he worked on it more and has more details about it.

**Comment by jessesimpson36** [comment]
Won't optimize be part of the monorepo for future releases and not camunda-optimize?

**Comment by jessesimpson36** [comment]
It looks like the release notes in the monorepo don't have any content.
https://github.com/camunda/camunda/releases/tag/8.6.0-optimize

for the release notes tool inside this repo, it needs a source with actual release notes. If that's in the camunda/camunda repo, then this repo should fetch from there instead of camunda-optimize. I would suggest figuring out how the release notes will be in the camunda/camunda repo before trying to change the camunda-platform repo.

**Comment by misiekhardcore** [comment]
Okay, I close this for now until we get clearer view on what needs to be done here especially that the release notes generation is looked into in general in the monorepo

**Pull request closed without merging**
