### PR TITLE
feat(web-modeler): pre-configure local Zeebe cluster

### PR DESCRIPTION
**Pull request by jfriedenstab**
Closes https://github.com/camunda/web-modeler/issues/10773

### CODE REVIEW

**Comment by jfriedenstab** [comment]
@wollefitz I think we should only merge this PR after the `8.6.0` release when the cluster configuration feature is available.

**Review by wollefitz — APPROVED** [review]
Thanks a bunch for refactoring the `README` so nicely!

Agree that this should only be merged **after** the `8.6` release and then be applied to the compose files for the first `8.7-alpha`. Let's convert this to draft in the meantime.

**Comment by jfriedenstab** [comment]
@wollefitz Yes, what I actually meant was to merge the PR as part of the 8.6.0 release (assuming that the feature will be ready in Web Modeler 8.6.0) 🙂.

**Comment by jessesimpson36** [comment]
@jfriedenstab you do not need to wait for 8.6 to be released, since this repo has 2 projects in it. the `docker-compose` folder with the images already targetting 8.6-alphaX,  and the root-level docker-compose.yaml which points to the latest 8.5 release. your change only targets the one already targetting 8.6.

**Comment by jessesimpson36** [comment]
I am also testing this now.

**Comment by wollefitz** [comment]
> @jfriedenstab you do not need to wait for 8.6 to be released, since this repo has 2 projects in it. the `docker-compose` folder with the images already targetting 8.6-alphaX, and the root-level docker-compose.yaml which points to the latest 8.5 release. your change only targets the one already targetting 8.6.

@jessesimpson36 Thanks for the explanation! This is more about the Web Modeler side though - we are not 100% certain yet if the feature will make it into `8.6` stable which is why we'd like to merge this PR only when we know more (probably next week Tuesday).

**Comment by jessesimpson36** [comment]
I see. Thanks for letting me know.

**Comment by jessesimpson36** [comment]
@jfriedenstab , what does it look like for it to be working? when I read the title of this PR, I would expect these things pre-filled, but this is what I get.

2024-09-20-100629_grim

**Comment by jfriedenstab** [comment]
@jessesimpson36 That is because the cluster configuration is not yet used in the current alpha version of Web Modeler 🙂. The respective changes will only be ready (hopefully) in the 8.6.0 release (see also Wolfgang's [comment](https://github.com/camunda/camunda-platform/pull/860#issuecomment-2363684247) above).

**Comment by jessesimpson36** [comment]
Alright, I misinterpreted the message about it being "fixed" after changing the port number.

**Pull request merged**
